<?php

/**
 * BaseCFType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $CFRule
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getCFRule() Returns the current record's "CFRule" collection
 * @method CFType              setId()     Sets the current record's "id" value
 * @method CFType              setName()   Sets the current record's "name" value
 * @method CFType              setCFRule() Sets the current record's "CFRule" collection
 * 
 * @package    router
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCFType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.cf_types');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CFRule', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}