<?php

/**
 * BaseInetChannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $ip
 * @property string $gw
 * @property string $iface
 * @property Doctrine_Collection $Identity
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getIp()       Returns the current record's "ip" value
 * @method string              getGw()       Returns the current record's "gw" value
 * @method string              getIface()    Returns the current record's "iface" value
 * @method Doctrine_Collection getIdentity() Returns the current record's "Identity" collection
 * @method InetChannel         setId()       Sets the current record's "id" value
 * @method InetChannel         setName()     Sets the current record's "name" value
 * @method InetChannel         setIp()       Sets the current record's "ip" value
 * @method InetChannel         setGw()       Sets the current record's "gw" value
 * @method InetChannel         setIface()    Sets the current record's "iface" value
 * @method InetChannel         setIdentity() Sets the current record's "Identity" collection
 * 
 * @package    router
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInetChannel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.inet_channels');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ip', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gw', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('iface', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Identity', array(
             'local' => 'id',
             'foreign' => 'inet_channels_id'));
    }
}