<?php

/**
 * BaseWorkPlace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $mac
 * @property string $ip
 * 
 * @method string    getMac() Returns the current record's "mac" value
 * @method string    getIp()  Returns the current record's "ip" value
 * @method WorkPlace setMac() Sets the current record's "mac" value
 * @method WorkPlace setIp()  Sets the current record's "ip" value
 * 
 * @package    router
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkPlace extends Identity
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('public.work_places');
        $this->hasColumn('mac', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ip', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}