<?php

/**
 * BaseCFProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_en
 * @property boolean $is_def_allowed
 * @property Doctrine_Collection $CFRule
 * @property Doctrine_Collection $Identity
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getNameEn()         Returns the current record's "name_en" value
 * @method boolean             getIsDefAllowed()   Returns the current record's "is_def_allowed" value
 * @method Doctrine_Collection getCFRule()         Returns the current record's "CFRule" collection
 * @method Doctrine_Collection getIdentity()       Returns the current record's "Identity" collection
 * @method CFProfile           setId()             Sets the current record's "id" value
 * @method CFProfile           setName()           Sets the current record's "name" value
 * @method CFProfile           setNameEn()         Sets the current record's "name_en" value
 * @method CFProfile           setIsDefAllowed()   Sets the current record's "is_def_allowed" value
 * @method CFProfile           setCFRule()         Sets the current record's "CFRule" collection
 * @method CFProfile           setIdentity()       Sets the current record's "Identity" collection
 * 
 * @package    router
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCFProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.cf_profiles');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('name_en', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_def_allowed', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CFRule', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $this->hasMany('Identity', array(
             'local' => 'id',
             'foreign' => 'profile_id'));
    }
}