<?php

/**
 * CFProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CFProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CFProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CFProfile');
    }
}