<?php

/**
 * CFTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CFTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CFTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CFType');
    }
}