<?php

/**
 * InetChannelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InetChannelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InetChannelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InetChannel');
    }
}