<?php

/**
 * WorkPlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkPlaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkPlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkPlace');
    }
}