<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/02 10:23:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=10.10.4.66;dbname=router',
  'username' => 'postgres',
  'password' => NULL,
  'name' => 'doctrine',
)),);
