<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/05/03 16:04:45
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinerecord' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sftesterdoctrine' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinegenerator' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineexception' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfwebdebugpaneldoctrine' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrinepager' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfformdoctrine' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrineroute' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfwidgetformdoctrinechoice' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinedataloadtask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebuildfilterstask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuildtask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuildmodeltask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedropdbtask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildsqltask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrineinsertsqltask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildschematask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinedatadumptask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegenerateadmintask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinemigratetask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinecreatemodeltables' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedqltask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildformstask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuilddbtask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebasetask' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinecli' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'swift_doctrinespool' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrineconnectionlistener' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/usr/local/www/router/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',

  // project
  'baseform' => '/usr/local/www/router/lib/form/BaseForm.class.php',
  'addcfprofileform' => '/usr/local/www/router/lib/form/AddCFProfileForm.class.php',
  'addidentityform' => '/usr/local/www/router/lib/form/AddIdentityForm.class.php',
  'cfruleform' => '/usr/local/www/router/lib/form/CFRuleForm.class.php',
  'workplaceupdateform' => '/usr/local/www/router/lib/form/WorkPlaceUpdateForm.class.php',
  'cfprofileupdateform' => '/usr/local/www/router/lib/form/CFProfileUpdateForm.class.php',

  // project_model
  'cfprofile' => '/usr/local/www/router/lib/model/doctrine/CFProfile.class.php',
  'cfprofiletable' => '/usr/local/www/router/lib/model/doctrine/CFProfileTable.class.php',
  'cfrule' => '/usr/local/www/router/lib/model/doctrine/CFRule.class.php',
  'cfruletable' => '/usr/local/www/router/lib/model/doctrine/CFRuleTable.class.php',
  'cftype' => '/usr/local/www/router/lib/model/doctrine/CFType.class.php',
  'cftypetable' => '/usr/local/www/router/lib/model/doctrine/CFTypeTable.class.php',
  'identity' => '/usr/local/www/router/lib/model/doctrine/Identity.class.php',
  'identitytable' => '/usr/local/www/router/lib/model/doctrine/IdentityTable.class.php',
  'inetchannel' => '/usr/local/www/router/lib/model/doctrine/InetChannel.class.php',
  'inetchanneltable' => '/usr/local/www/router/lib/model/doctrine/InetChannelTable.class.php',
  'workplace' => '/usr/local/www/router/lib/model/doctrine/WorkPlace.class.php',
  'workplacetable' => '/usr/local/www/router/lib/model/doctrine/WorkPlaceTable.class.php',
  'basecfprofile' => '/usr/local/www/router/lib/model/doctrine/base/BaseCFProfile.class.php',
  'basecfrule' => '/usr/local/www/router/lib/model/doctrine/base/BaseCFRule.class.php',
  'basecftype' => '/usr/local/www/router/lib/model/doctrine/base/BaseCFType.class.php',
  'baseidentity' => '/usr/local/www/router/lib/model/doctrine/base/BaseIdentity.class.php',
  'baseinetchannel' => '/usr/local/www/router/lib/model/doctrine/base/BaseInetChannel.class.php',
  'baseworkplace' => '/usr/local/www/router/lib/model/doctrine/base/BaseWorkPlace.class.php',

  // application
  'myuser' => '/usr/local/www/router/apps/backend/lib/myUser.class.php',

  // modules
);
