<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/08 13:19:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=router',
  'username' => 'oper',
  'password' => NULL,
  'name' => 'doctrine',
)),);
